# 100 Numpy Exercises solved in PyTorch


**Symbols**: 
- 🆘： need some help to improve the solution
- 🔧： do some rewrite to the problem
- 🚫： ignore the problem

## 1. Import the torch package(★☆☆)

In [1]:
import torch

## 2. Print the torch version and the configuration (★☆☆)

In [2]:
print(torch.__version__)
print(f"CUDA Availability: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA Version: {torch.version.cuda}")
    print(f"CUDA Device Count: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"Device {i}: {torch.cuda.get_device_name(i)}")

2.5.1+cu121
CUDA Availability: True
CUDA Version: 12.1
CUDA Device Count: 1
Device 0: NVIDIA GeForce RTX 4060 Ti


## 3. Create a null vector of size 10 (★☆☆)


In [3]:
z = torch.zeros(10)
z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
z = torch.zeros((10,))
z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. How to find the memory size of any array (★☆☆)

In [5]:
z = torch.zeros(10)
z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
z.dtype, z.element_size()

(torch.float32, 4)

In [7]:
print("%d bytes" % (z.numel() * z.element_size()))

40 bytes


## 5. How to get the documentation of the torch add function from the command line? (★☆☆)

In [8]:
!python -c "import torch; help(torch.add)"

Help on built-in function add in module torch:

add(...)
    add(input, other, *, alpha=1, out=None) -> Tensor

    Adds :attr:`other`, scaled by :attr:`alpha`, to :attr:`input`.

    .. math::
        \text{{out}}_i = \text{{input}}_i + \text{{alpha}} \times \text{{other}}_i


    Supports :ref:`broadcasting to a common shape <broadcasting-semantics>`,
    :ref:`type promotion <type-promotion-doc>`, and integer, float, and complex inputs.

    Args:
        input (Tensor): the input tensor.
        other (Tensor or Number): the tensor or number to add to :attr:`input`.

    Keyword arguments:
        alpha (Number): the multiplier for :attr:`other`.
        out (Tensor, optional): the output tensor.

    Examples::

        >>> a = torch.randn(4)
        >>> a
        tensor([ 0.0202,  1.0985,  1.3506, -0.6056])
        >>> torch.add(a, 20)
        tensor([ 20.0202,  21.0985,  21.3506,  19.3944])

        >>> b = torch.randn(4)
        >>> b
        tensor([-0.9732, -0.3497,  0.6245, 

## 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
z = torch.zeros(10)
z[4] = 1
z

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
z = torch.arange(10, 50)
z

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

## 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
z = torch.arange(50)
z.flip(dims=[0])

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
z = torch.arange(0, 9).reshape(3, 3)
z

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
z = torch.tensor([1, 2, 0, 0, 4, 0])
torch.nonzero(z)

tensor([[0],
        [1],
        [4]])

## 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
z = torch.eye(3)
z

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
z = torch.rand((3, 3, 3))
z

tensor([[[0.5373, 0.0987, 0.9975],
         [0.8067, 0.1883, 0.4007],
         [0.6270, 0.1260, 0.7449]],

        [[0.0398, 0.7708, 0.3449],
         [0.1538, 0.5491, 0.5382],
         [0.1945, 0.0316, 0.9182]],

        [[0.6734, 0.2762, 0.5440],
         [0.2755, 0.8292, 0.3843],
         [0.6685, 0.5783, 0.5963]]])

## 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
z = torch.rand((10, 10))
z

tensor([[0.4847, 0.6608, 0.1807, 0.5162, 0.6868, 0.9089, 0.6760, 0.8488, 0.0264,
         0.2415],
        [0.4256, 0.1857, 0.9420, 0.9065, 0.0609, 0.6046, 0.3080, 0.7818, 0.6709,
         0.7705],
        [0.1222, 0.7682, 0.2892, 0.8979, 0.8815, 0.9825, 0.9194, 0.2914, 0.9830,
         0.7049],
        [0.9772, 0.6086, 0.3138, 0.0567, 0.8133, 0.0433, 0.9546, 0.7593, 0.8447,
         0.1365],
        [0.2580, 0.5604, 0.1709, 0.7541, 0.3692, 0.3767, 0.3834, 0.3293, 0.2233,
         0.4259],
        [0.6422, 0.0406, 0.0743, 0.0847, 0.3497, 0.2500, 0.2615, 0.6489, 0.4792,
         0.9997],
        [0.4601, 0.5720, 0.5372, 0.9424, 0.9932, 0.6861, 0.6770, 0.4079, 0.6610,
         0.2880],
        [0.8998, 0.9897, 0.2213, 0.7661, 0.6601, 0.7374, 0.3961, 0.7111, 0.8696,
         0.4879],
        [0.0499, 0.6597, 0.5283, 0.8830, 0.3274, 0.8259, 0.2624, 0.8420, 0.6111,
         0.2981],
        [0.9126, 0.0900, 0.3551, 0.8958, 0.0921, 0.2008, 0.9180, 0.0201, 0.3903,
         0.1550]])

In [17]:
z.min(), z.max()

(tensor(0.0201), tensor(0.9997))

## 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
z = torch.rand(30)
z.mean()

tensor(0.5628)

## 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [19]:
z = torch.ones(10, 10)
z[1:-1, 1:-1] = 0
z

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
z = torch.ones(5, 5)
z

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
border_width = 1
torch.nn.functional.pad(z, 
                        pad=(border_width, border_width, border_width, border_width), 
                        mode='constant',
                        value=0,
                       )

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

## 17. What is the result of the following expression? (★☆☆)
```python
0 * torch.nan
torch.nan == torch.nan
torch.inf > torch.nan
torch.nan - torch.nan
torch.nan in set([torch.nan])
0.3 == 3 * 0.1
```

In [22]:
0 * torch.nan

nan

In [23]:
torch.nan == torch.nan

False

In [24]:
torch.inf > torch.nan

False

In [25]:
torch.nan - torch.nan

nan

In [26]:
torch.nan in set([torch.nan])

True

In [27]:
0.3 == 3 * 0.1

False

## 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [28]:
z = torch.tensor([1, 2, 3, 4])
torch.diag(z, diagonal=-1) 

tensor([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]])

## 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [29]:
z = torch.zeros((8, 8))
z[1::2, ::2] = 1  # rows: 2, 4, 6, 8
z[::2, 1::2] = 1  # rows: 1， 3， 5， 7
z

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [30]:
torch.unravel_index(torch.tensor(99), (6, 7, 8))

(tensor(1), tensor(5), tensor(3))

## 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [31]:
z = torch.tile( torch.tensor([[0, 1], [1, 0]]), (4,4))
z

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])

## 22. Normalize a 5x5 random matrix (★☆☆)

In [32]:
z = torch.rand((5,5))
z = (z - torch.mean (z)) / (torch.std (z))
z

tensor([[ 0.9085,  0.2110, -0.4609, -0.5940,  1.3321],
        [-0.0455, -0.8614,  0.5499, -1.8999,  0.1982],
        [ 0.5237, -0.1254, -0.2810, -0.2465, -1.3676],
        [ 1.5506,  0.4986, -1.3437,  0.0122,  1.2983],
        [ 0.5542,  0.4247, -0.4020, -2.0755,  1.6413]])

## 23. 🚫Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

We cannot do this in PyTorch.

## 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [33]:
z = torch.matmul(torch.ones((5, 3)), torch.ones((3, 2)))
z

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])

## 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [34]:
z = torch.arange(11)
z[(3 < z) & (z < 8)] *= -1
z

tensor([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

## 26. 🚫What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

We cannot do this in PyTorch.

## 27. Consider an integer vector z, which of these expressions are legal? (★☆☆)
```python
z**z
2 << z >> 2
z <- z
1j*z
z/1/1
z<z>z

```

In [35]:
z = torch.arange(10)
z

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# 1
z ** z

tensor([        1,         1,         4,        27,       256,      3125,
            46656,    823543,  16777216, 387420489])

In [37]:
# 2
print(2 << z >> 2)
print((2 << z) >> 2)

tensor([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])
tensor([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256])


In [38]:
# 3
print(z <- z)
print(z < (-z))

tensor([False, False, False, False, False, False, False, False, False, False])
tensor([False, False, False, False, False, False, False, False, False, False])


In [39]:
# 3
import dis

dis.dis('z <- z')

  0           RESUME                   0

  1           LOAD_NAME                0 (z)
              LOAD_NAME                0 (z)
              UNARY_NEGATIVE
              COMPARE_OP               2 (<)
              RETURN_VALUE


In [40]:
# 4
1j*z

tensor([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j, 0.+8.j, 0.+9.j])

In [41]:
# 5
print(z/1/1)
print((z/1)/1)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [42]:
# 6
try:
    print(z<z>z)
except Exception as e:
    print(e)

Boolean value of Tensor with more than one value is ambiguous


## 28. What are the result of the following expressions? (★☆☆)
```python
torch.tensor(0) / torch.tensor(0)
torch.tensor(0) // torch.tensor(0)
torch.tensor([torch.nan]).to(torch.int).to(torch.float)
```

In [43]:
torch.tensor(0) / torch.tensor(0)

tensor(nan)

In [44]:
try:
    torch.tensor(0) // torch.tensor(0)
except Exception as e:
    print(e)

ZeroDivisionError


In [45]:
torch.tensor([torch.nan]).to(torch.int).to(torch.float)

tensor([-2.1475e+09])

## 29. How to round away from zero a float array ? (★☆☆)

In [46]:
z = torch.randn((10))
z

tensor([-0.4848,  1.7904,  0.8012,  1.4280,  1.4842, -0.8127,  1.5392,  0.2753,
        -0.1902,  0.3936])

In [47]:
torch.copysign(torch.ceil(torch.abs(z)), z)

tensor([-1.,  2.,  1.,  2.,  2., -1.,  2.,  1., -1.,  1.])

In [48]:
torch.where(z>0, torch.ceil(z), torch.floor(z))

tensor([-1.,  2.,  1.,  2.,  2., -1.,  2.,  1., -1.,  1.])

## 30. 🆘How to find common values between two arrays? (★☆☆)

In [72]:
z1 = torch.randint(0, 10, (10, ))
z2 = torch.randint(0, 10, (10, ))
print(f"{z1=}\n{z2=}")

z1=tensor([1, 3, 9, 0, 3, 5, 0, 2, 1, 1])
z2=tensor([8, 5, 1, 1, 2, 7, 3, 9, 5, 2])


In [73]:
set(z1.tolist()) & set(z2.tolist())

{1, 2, 3, 5, 9}

## 31. How to ignore all torch warnings (not recommended)? (★☆☆)

In [99]:
torch.autograd.detect_anomaly()

/tmp/ipykernel_74417/675420015.py:1: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  torch.autograd.detect_anomaly()


In [100]:
import warnings
class IgnoreWarnings:
    def __enter__(self):
        warnings.filterwarnings("ignore")

    def __exit__(self, exc_type, exc_val, exc_tb):
        warnings.resetwarnings()

with IgnoreWarnings():
    torch.autograd.detect_anomaly()

In [101]:
torch.autograd.detect_anomaly()

/tmp/ipykernel_74417/675420015.py:1: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  torch.autograd.detect_anomaly()


## 32. 🔧How to get the square root of a complex value in torch (★☆☆)


In [110]:
real = torch.tensor(-1, dtype=torch.float32)
imag = torch.tensor(0, dtype=torch.float32)
x = torch.complex(real, imag)
x

tensor(-1.+0.j)

In [111]:
torch.sqrt(x)

tensor(0.+1.j)

## 33. 🚫How to get the dates of yesterday, today and tomorrow? (★☆☆)

## 34. 🚫How to get all the dates corresponding to the month of July 2016? (★★☆)

## 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [145]:
A = torch.ones(3) * 1
B = torch.ones(3) * 2
A, B

(tensor([1., 1., 1.]), tensor([2., 2., 2.]))

In [146]:
torch.add(A, B, out=B)
B

tensor([3., 3., 3.])

In [147]:
torch.divide(A, 2, out=A)
torch.neg(A, out=A)
A

tensor([-0.5000, -0.5000, -0.5000])

In [148]:
torch.multiply(B, A, out=A)

tensor([-1.5000, -1.5000, -1.5000])

## 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [153]:
z = 10 * torch.rand(10)
z

tensor([5.7646, 2.4064, 8.9948, 4.1502, 3.3484, 6.1644, 4.5045, 9.4773, 7.9727,
        1.9132])

In [155]:
# solution1
z - z % 1

tensor([5., 2., 8., 4., 3., 6., 4., 9., 7., 1.])

In [156]:
# solution2
z // 1

tensor([5., 2., 8., 4., 3., 6., 4., 9., 7., 1.])

In [158]:
# solution3
z.int()

tensor([5, 2, 8, 4, 3, 6, 4, 9, 7, 1], dtype=torch.int32)

In [159]:
# solution4
torch.trunc(z)

tensor([5., 2., 8., 4., 3., 6., 4., 9., 7., 1.])

## 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [161]:
# solution1
torch.zeros(5, 5) + torch.arange(5)

tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]])

In [173]:
# solution2
torch.tile(torch.arange(5), dims=(5, 1))

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

## 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

https://stackoverflow.com/questions/55307368/creating-a-torch-tensor-from-a-generator

In [175]:
import numpy as np

def generate():
    for x in range(10):
        yield x
z = torch.from_numpy(np.fromiter(generate(),dtype=float,count=-1))
z

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

## 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [187]:
torch.linspace(start=0, end=1, steps=12)[1:-1]

tensor([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273, 0.8182,
        0.9091])

## 40. Create a random vector of size 10 and sort it (★★☆)

In [189]:
z = torch.rand(10)
z

tensor([0.0476, 0.8197, 0.2549, 0.1986, 0.8609, 0.6635, 0.9528, 0.5135, 0.2743,
        0.3946])

In [194]:
z = z.sort()
z

torch.return_types.sort(
values=tensor([0.0476, 0.1986, 0.2549, 0.2743, 0.3946, 0.5135, 0.6635, 0.8197, 0.8609,
        0.9528]),
indices=tensor([0, 3, 2, 8, 9, 7, 5, 1, 4, 6]))

## 🔧41. How to sum a small array faster? (★★☆)


1. `np.sum`
2. `torch.sum`
3. `np.add.reduce`
4. `sum` in python
5. `for` and `+` in python

In [20]:
import numpy as np

z_torch = torch.arange(10)
z_numpy = np.arange(10)
z_python = [i for i in range(10)]

z_torch, z_numpy, z_python

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# method 1
%timeit np.sum(z_numpy)

1.65 μs ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [24]:
# method 2
%timeit torch.sum(z_torch)

1.28 μs ± 6.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [26]:
# method 3
%timeit np.add.reduce(z_numpy)

831 ns ± 2.35 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [27]:
# method 4
%timeit sum(z_python)

64.9 ns ± 0.306 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [28]:
# method 5
def sum_with_for_loop():
    n = 0
    for i in z_python:
        n += i
    return n

%timeit sum_with_for_loop

8.51 ns ± 0.0571 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


## 42. Consider two random array/tensor A and B, check if they are equal (★★☆)

In [50]:
t1 = torch.randint(0, 2, (5, ))
t2 = torch.randint(0, 2, (5, ))

t1, t2

(tensor([0, 1, 0, 0, 1]), tensor([0, 1, 0, 0, 1]))

In [55]:
# The behaviour of this function is analogous to `numpy.allclose`
torch.allclose(t1, t2)

True

In [56]:
# Computes element-wise equality
torch.eq(t1, t2)

tensor([True, True, True, True, True])

## 43.  🚫Make an array/tensor immutable (read-only) (★★☆)

https://github.com/pytorch/pytorch/issues/44027

## 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [62]:
z = torch.rand((10, 2))
x, y = z[:, 0], z[:, 1]
r = torch.sqrt(x**2 + y ** 2)
t = torch.arctan2(y, x)

r, t

(tensor([1.1658, 0.8590, 0.7153, 0.9412, 1.0065, 0.6229, 0.0637, 1.3276, 0.4689,
         1.0837]),
 tensor([0.6077, 0.7141, 0.0409, 0.2322, 0.4560, 0.8626, 0.5504, 0.7723, 0.8890,
         1.0532]))

## 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [66]:
z = torch.rand(10)
print(f"Before: {z}")

z[z.argmax()] = 0
print(f"After: {z}")

Before: tensor([0.6948, 0.1091, 0.7240, 0.5685, 0.7686, 0.7866, 0.0311, 0.9583, 0.5142,
        0.1780])
After: tensor([0.6948, 0.1091, 0.7240, 0.5685, 0.7686, 0.7866, 0.0311, 0.0000, 0.5142,
        0.1780])


In [67]:
z = torch.rand(10)
print(f"Before: {z}")

z[z == z.max()] = 0
print(f"After: {z}")

Before: tensor([0.3117, 0.1246, 0.6908, 0.5892, 0.9242, 0.7525, 0.6414, 0.5580, 0.7929,
        0.9808])
After: tensor([0.3117, 0.1246, 0.6908, 0.5892, 0.9242, 0.7525, 0.6414, 0.5580, 0.7929,
        0.0000])


## 🚫46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

## 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

$$
C_{ij} = \frac{1}{x_i - y_j}
$$

In [69]:
x = torch.arange(8)
y = x + 0.5

x, y

(tensor([0, 1, 2, 3, 4, 5, 6, 7]),
 tensor([0.5000, 1.5000, 2.5000, 3.5000, 4.5000, 5.5000, 6.5000, 7.5000]))

In [95]:
# c = 1 / (x.unsqueeze(1) - y.unsqueeze(0))
c = 1 / (x.reshape(8, 1) - y.reshape(1, 8))
c

tensor([[-2.0000, -0.6667, -0.4000, -0.2857, -0.2222, -0.1818, -0.1538, -0.1333],
        [ 2.0000, -2.0000, -0.6667, -0.4000, -0.2857, -0.2222, -0.1818, -0.1538],
        [ 0.6667,  2.0000, -2.0000, -0.6667, -0.4000, -0.2857, -0.2222, -0.1818],
        [ 0.4000,  0.6667,  2.0000, -2.0000, -0.6667, -0.4000, -0.2857, -0.2222],
        [ 0.2857,  0.4000,  0.6667,  2.0000, -2.0000, -0.6667, -0.4000, -0.2857],
        [ 0.2222,  0.2857,  0.4000,  0.6667,  2.0000, -2.0000, -0.6667, -0.4000],
        [ 0.1818,  0.2222,  0.2857,  0.4000,  0.6667,  2.0000, -2.0000, -0.6667],
        [ 0.1538,  0.1818,  0.2222,  0.2857,  0.4000,  0.6667,  2.0000, -2.0000]])

In [98]:
np.linalg.det(c)

np.float32(3638.1638)

## 48. Print the minimum and maximum representable value for each torch scalar type (★★☆)

In [111]:
for dtype in [torch.int8, torch.int16, torch.int32, torch.int64]:
    print(f"{dtype}.min: {torch.iinfo(dtype).min}")
    print(f"{dtype}.max: {torch.iinfo(dtype).max}")
    print("="*42)
    
for dtype in [torch.float32, torch.float64]:
    print(f"{dtype}.min: {torch.finfo(dtype).min}")
    print(f"{dtype}.max: {torch.finfo(dtype).max}")
    print(f"{dtype}.eps: {torch.finfo(dtype).eps}")
    print("="*42)

torch.int8.min: -128
torch.int8.max: 127
torch.int16.min: -32768
torch.int16.max: 32767
torch.int32.min: -2147483648
torch.int32.max: 2147483647
torch.int64.min: -9223372036854775808
torch.int64.max: 9223372036854775807
torch.float32.min: -3.4028234663852886e+38
torch.float32.max: 3.4028234663852886e+38
torch.float32.eps: 1.1920928955078125e-07
torch.float64.min: -1.7976931348623157e+308
torch.float64.max: 1.7976931348623157e+308
torch.float64.eps: 2.220446049250313e-16


## 49. How to print all the values(without ellipses: `...`) of an array/tensor? (★★☆)

In [128]:
z = torch.ones((40, 40))
print(z)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])


In [129]:
# Limit the number of elements shown
torch.set_printoptions(threshold=torch.inf)
print(z)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

In [133]:
# to recover the default print options
torch.set_printoptions(threshold=1000, precision=4)

## 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [152]:
z = torch.arange(100)
v = torch.randint(0, 100, (1,))

z, v

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
         54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
         72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
         90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 tensor([29]))

In [154]:
index = (z - v).abs().argmin()

index, z[index]

(tensor(29), tensor(29))

## 🚫51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

## 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [158]:
def pairwise_distances(coords):
  """
  Calculates pairwise distances between points in a tensor of coordinates.

  Args:
    coords: A PyTorch tensor of shape (N, 2) where N is the number of points 
            and each row represents the (x, y) coordinates of a point.

  Returns:
    A PyTorch tensor of shape (N, N) containing the pairwise distances.
  """
  # Calculate pairwise differences along each dimension
  x_diff = coords[:, 0].unsqueeze(1) - coords[:, 0] 
  y_diff = coords[:, 1].unsqueeze(1) - coords[:, 1]

  # Compute squared distances
  squared_dists = x_diff ** 2 + y_diff ** 2

  # Compute Euclidean distances
  distances = torch.sqrt(squared_dists)

  return distances

# Example usage
coords = torch.randn(100, 2)  # Generate 100 random 2D points
distances = pairwise_distances(coords)
print(distances.shape)
print(distances) 

torch.Size([100, 100])
tensor([[0.0000, 1.5254, 1.2953,  ..., 0.7519, 1.2113, 1.0398],
        [1.5254, 0.0000, 0.3097,  ..., 1.3497, 1.7384, 2.3526],
        [1.2953, 0.3097, 0.0000,  ..., 1.2639, 1.4301, 2.0619],
        ...,
        [0.7519, 1.3497, 1.2639,  ..., 0.0000, 1.8521, 1.7781],
        [1.2113, 1.7384, 1.4301,  ..., 1.8521, 0.0000, 1.0360],
        [1.0398, 2.3526, 2.0619,  ..., 1.7781, 1.0360, 0.0000]])


## 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [172]:
# Create a float tensor
float_tensor = torch.tensor([1.5, 2.7, 3.2], dtype=torch.float32)

# Convert to int in-place
float_tensor.data = float_tensor.to(torch.int32)

print(float_tensor)

tensor([1, 2, 3], dtype=torch.int32)


## 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```


In [177]:
import numpy as np
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
z = torch.from_numpy(np.genfromtxt(s, delimiter=",", dtype=np.int32))
z

tensor([[ 1,  2,  3,  4,  5],
        [ 6, -1, -1,  7,  8],
        [-1, -1,  9, 10, 11]], dtype=torch.int32)

## 55. What is the equivalent of enumerate for torch tensors? (★★☆)

In [181]:
def iterate_tensor(tensor):
  """
  Iterates over all values in a PyTorch tensor of any dimension.

  Args:
    tensor: The input PyTorch tensor.

  Yields:
    A tuple containing:
      - The current value of the tensor.
      - A tuple of indices representing the position of the value in the tensor.
  """
  shape = tensor.shape
  indices = torch.zeros(len(shape), dtype=torch.long)  # Initialize indices

  while True:
    yield tensor[tuple(indices)], tuple(indices)

    # Increment indices
    dim = 0
    while dim < len(shape):
      indices[dim] += 1
      if indices[dim] < shape[dim]:
        break
      else:
        indices[dim] = 0
        dim += 1

    # Check if all indices have reached the end
    if dim == len(shape):
      break

In [185]:
z = np.arange(9).reshape(3,3)

In [186]:
for value, indices in iterate_tensor(z):
    print(f"Value: {value}, Indices: {indices}") 

Value: 0, Indices: (tensor(0), tensor(0))
Value: 3, Indices: (tensor(1), tensor(0))
Value: 6, Indices: (tensor(2), tensor(0))
Value: 1, Indices: (tensor(0), tensor(1))
Value: 4, Indices: (tensor(1), tensor(1))
Value: 7, Indices: (tensor(2), tensor(1))
Value: 2, Indices: (tensor(0), tensor(2))
Value: 5, Indices: (tensor(1), tensor(2))
Value: 8, Indices: (tensor(2), tensor(2))


## 56. Generate a generic 2D Gaussian-like array (★★☆)