# 100 Numpy Exercises solved in PyTorch

## 1. Import the torch package(★☆☆)

In [1]:
import torch

## 2. Print the torch version and the configuration (★☆☆)

In [26]:
print(torch.__version__)
print(f"CUDA Availability: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA Version: {torch.version.cuda}")
    print(f"CUDA Device Count: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"Device {i}: {torch.cuda.get_device_name(i)}")

2.5.1+cu121
CUDA Availability: True
CUDA Version: 12.1
CUDA Device Count: 1
Device 0: NVIDIA GeForce RTX 4060 Ti


## 3. Create a null vector of size 10 (★☆☆)


In [30]:
Z = torch.zeros(10)
Z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
Z = torch.zeros((10,))
Z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. How to find the memory size of any array (★☆☆)

In [9]:
Z = torch.zeros(10)
Z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
Z.dtype, Z.element_size()

(torch.float32, 4)

In [18]:
print("%d bytes" % (Z.numel() * Z.element_size()))

40 bytes


## 5. How to get the documentation of the torch add function from the command line? (★☆☆)

In [23]:
!python -c "import torch; help(torch.add)"

Help on built-in function add in module torch:

add(...)
    add(input, other, *, alpha=1, out=None) -> Tensor

    Adds :attr:`other`, scaled by :attr:`alpha`, to :attr:`input`.

    .. math::
        \text{{out}}_i = \text{{input}}_i + \text{{alpha}} \times \text{{other}}_i


    Supports :ref:`broadcasting to a common shape <broadcasting-semantics>`,
    :ref:`type promotion <type-promotion-doc>`, and integer, float, and complex inputs.

    Args:
        input (Tensor): the input tensor.
        other (Tensor or Number): the tensor or number to add to :attr:`input`.

    Keyword arguments:
        alpha (Number): the multiplier for :attr:`other`.
        out (Tensor, optional): the output tensor.

    Examples::

        >>> a = torch.randn(4)
        >>> a
        tensor([ 0.0202,  1.0985,  1.3506, -0.6056])
        >>> torch.add(a, 20)
        tensor([ 20.0202,  21.0985,  21.3506,  19.3944])

        >>> b = torch.randn(4)
        >>> b
        tensor([-0.9732, -0.3497,  0.6245, 

## 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [27]:
Z = torch.zeros(10)
Z[4] = 1
Z

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [29]:
Z = torch.arange(10, 50)
Z

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

## 8. Reverse a vector (first element becomes last) (★☆☆)

In [43]:
Z = torch.arange(50)
Z.flip(dims=[0])

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [45]:
Z = torch.arange(0, 9).reshape(3, 3)
Z

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [50]:
Z = torch.tensor([1, 2, 0, 0, 4, 0])
torch.nonzero(Z)

tensor([[0],
        [1],
        [4]])

## 11. Create a 3x3 identity matrix (★☆☆)

In [52]:
Z = torch.eye(3)
Z

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## 12. Create a 3x3x3 array with random values (★☆☆)

In [53]:
Z = torch.rand((3, 3, 3))
Z

tensor([[[0.7813, 0.2612, 0.7086],
         [0.3905, 0.4764, 0.1822],
         [0.2762, 0.1877, 0.2254]],

        [[0.7068, 0.5508, 0.4650],
         [0.2931, 0.3319, 0.1810],
         [0.8676, 0.3075, 0.2974]],

        [[0.3338, 0.5629, 0.6650],
         [0.9427, 0.0776, 0.0887],
         [0.7359, 0.2024, 0.2977]]])

## 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
Z = torch.rand((10, 10))
Z

tensor([[0.6987, 0.4993, 0.2781, 0.8940, 0.1022, 0.2070, 0.7184, 0.8178, 0.4489,
         0.5454],
        [0.3194, 0.7795, 0.6244, 0.1900, 0.5101, 0.4113, 0.4815, 0.6529, 0.5855,
         0.0858],
        [0.1310, 0.5084, 0.2668, 0.2484, 0.9237, 0.2983, 0.0529, 0.6257, 0.9961,
         0.5865],
        [0.7279, 0.9093, 0.3798, 0.0875, 0.2139, 0.2360, 0.4008, 0.3717, 0.8071,
         0.0961],
        [0.3141, 0.5027, 0.7829, 0.7604, 0.9908, 0.4907, 0.6133, 0.6458, 0.7186,
         0.1612],
        [0.9347, 0.2232, 0.3526, 0.7786, 0.1041, 0.1233, 0.4754, 0.5345, 0.3884,
         0.2370],
        [0.7211, 0.6968, 0.7469, 0.9882, 0.8844, 0.5487, 0.3475, 0.4388, 0.8117,
         0.4838],
        [0.0131, 0.4212, 0.4231, 0.2966, 0.6864, 0.0530, 0.6463, 0.9763, 0.8398,
         0.8613],
        [0.7454, 0.3713, 0.4090, 0.7979, 0.1844, 0.2741, 0.2071, 0.4391, 0.9204,
         0.8964],
        [0.1655, 0.7173, 0.9922, 0.5248, 0.4402, 0.2859, 0.8191, 0.3131, 0.3076,
         0.9152]])

In [57]:
Z.min(), Z.max()

(tensor(0.0131), tensor(0.9961))

## 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
Z = torch.rand(30)
Z.mean()

tensor(0.4322)

## 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [59]:
Z = torch.ones(10, 10)
Z[1:-1, 1:-1] = 0
Z

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [61]:
Z = torch.ones(5, 5)
Z

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [68]:
border_width = 1
torch.nn.functional.pad(Z, 
                        pad=(border_width, border_width, border_width, border_width), 
                        mode='constant',
                        value=0,
                       )

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

## 17. What is the result of the following expression? (★☆☆)
```python
0 * torch.nan
torch.nan == torch.nan
torch.inf > torch.nan
torch.nan - torch.nan
torch.nan in set([torch.nan])
0.3 == 3 * 0.1
```

In [70]:
0 * torch.nan

nan

In [71]:
torch.nan == torch.nan

False

In [72]:
torch.inf > torch.nan

False

In [73]:
torch.nan - torch.nan

nan

In [74]:
torch.nan in set([torch.nan])

True

In [75]:
0.3 == 3 * 0.1

False

## 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [76]:
Z = torch.tensor([1, 2, 3, 4])
torch.diag(Z, diagonal=-1) 

tensor([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]])

## 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [78]:
Z = torch.zeros((8, 8))
Z[1::2, ::2] = 1  # rows: 2, 4, 6, 8
Z[::2, 1::2] = 1  # rows: 1， 3， 5， 7
Z

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [87]:
torch.unravel_index(torch.tensor(99), (6, 7, 8))

(tensor(1), tensor(5), tensor(3))

## 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [3]:
Z = torch.tile( torch.tensor([[0, 1], [1, 0]]), (4,4))
Z

tensor([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])

## 22. Normalize a 5x5 random matrix (★☆☆)

In [13]:
Z = torch.rand((5,5))
Z = (Z - torch.mean (Z)) / (torch.std (Z))
Z

tensor([[ 2.3758, -0.1250, -1.0375,  0.0600, -0.0931],
        [-1.0247,  0.3465,  0.1357, -0.0830, -0.1694],
        [ 1.3879, -1.3475, -1.8516,  1.1368, -0.1087],
        [-1.2090, -0.1777,  0.3642,  1.4081, -0.5958],
        [-0.3453, -0.2897,  1.1209,  1.0911, -0.9690]])

## (Skip)23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

We cannot do this in PyTorch.

## 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [19]:
Z = torch.matmul(torch.ones((5, 3)), torch.ones((3, 2)))
Z

tensor([[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])

## 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [21]:
Z = torch.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
Z

tensor([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])